package org.taljaard.nextgear.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.taljaard.nextgear.mybatis.dao.Contracts;
import org.taljaard.nextgear.mybatis.dao.ContractsExample;

public interface ContractsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contracts
	 * @mbg.generated  Sun Feb 04 21:29:41 EST 2018
	 */
	@SelectProvider(type = ContractsSqlProvider.class, method = "countByExample")
	long countByExample(ContractsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contracts
	 * @mbg.generated  Sun Feb 04 21:29:41 EST 2018
	 */
	@DeleteProvider(type = ContractsSqlProvider.class, method = "deleteByExample")
	int deleteByExample(ContractsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contracts
	 * @mbg.generated  Sun Feb 04 21:29:41 EST 2018
	 */
	@Delete({ "delete from contracts", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contracts
	 * @mbg.generated  Sun Feb 04 21:29:41 EST 2018
	 */
	@Insert({ "insert into contracts (amountRequested, businessNumber, ", "activitationDate, name, ",
			"status, contractType, updateDate, ", "createDate)",
			"values (#{amountRequested,jdbcType=DECIMAL}, #{businessNumber,jdbcType=VARCHAR}, ",
			"#{activitationDate,jdbcType=TIMESTAMP}, #{name,jdbcType=VARCHAR}, ",
			"#{status,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, #{updateDate,jdbcType=TIMESTAMP}, ",
			"#{createDate,jdbcType=TIMESTAMP})" })
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insert(Contracts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contracts
	 * @mbg.generated  Sun Feb 04 21:29:41 EST 2018
	 */
	@InsertProvider(type = ContractsSqlProvider.class, method = "insertSelective")
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insertSelective(Contracts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contracts
	 * @mbg.generated  Sun Feb 04 21:29:41 EST 2018
	 */
	@SelectProvider(type = ContractsSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "amountRequested", property = "amountRequested", jdbcType = JdbcType.DECIMAL),
			@Result(column = "businessNumber", property = "businessNumber", jdbcType = JdbcType.VARCHAR),
			@Result(column = "activitationDate", property = "activitationDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "status", property = "status", jdbcType = JdbcType.VARCHAR),
			@Result(column = "contractType", property = "type", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateDate", property = "updateDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "createDate", property = "createDate", jdbcType = JdbcType.TIMESTAMP) })
	List<Contracts> selectByExample(ContractsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contracts
	 * @mbg.generated  Sun Feb 04 21:29:41 EST 2018
	 */
	@Select({ "select", "id, amountRequested, businessNumber, activitationDate, name, status, contractType, ",
			"updateDate, createDate", "from contracts", "where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "amountRequested", property = "amountRequested", jdbcType = JdbcType.DECIMAL),
			@Result(column = "businessNumber", property = "businessNumber", jdbcType = JdbcType.VARCHAR),
			@Result(column = "activitationDate", property = "activitationDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "status", property = "status", jdbcType = JdbcType.VARCHAR),
			@Result(column = "contractType", property = "type", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateDate", property = "updateDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "createDate", property = "createDate", jdbcType = JdbcType.TIMESTAMP) })
	Contracts selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contracts
	 * @mbg.generated  Sun Feb 04 21:29:41 EST 2018
	 */
	@UpdateProvider(type = ContractsSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Contracts record, @Param("example") ContractsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contracts
	 * @mbg.generated  Sun Feb 04 21:29:41 EST 2018
	 */
	@UpdateProvider(type = ContractsSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Contracts record, @Param("example") ContractsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contracts
	 * @mbg.generated  Sun Feb 04 21:29:41 EST 2018
	 */
	@UpdateProvider(type = ContractsSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Contracts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contracts
	 * @mbg.generated  Sun Feb 04 21:29:41 EST 2018
	 */
	@Update({ "update contracts", "set amountRequested = #{amountRequested,jdbcType=DECIMAL},",
			"businessNumber = #{businessNumber,jdbcType=VARCHAR},",
			"activitationDate = #{activitationDate,jdbcType=TIMESTAMP},", "name = #{name,jdbcType=VARCHAR},",
			"status = #{status,jdbcType=VARCHAR},", "contractType = #{type,jdbcType=VARCHAR},",
			"updateDate = #{updateDate,jdbcType=TIMESTAMP},", "createDate = #{createDate,jdbcType=TIMESTAMP}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Contracts record);
}